### ISSUE TITLE
프로젝트 주제 선정 미팅 - 2020.08.04 화요일

### ISSUE THREAD

**Issue by KJongHyun** [HollysParty/issue#1]
### 프로젝트 주제선정
- [x] 멀티 색칠하기 서비스
- [ ] 주신 투자 대회
- [ ] 메신저 서비스
- [ ] 여행지 식사 매칭
- [ ] 동적으로 사이트 제작 서비스 

### 기간 산정
phase1 -> 2달

## TODO
- [ ] 다음 미팅 날짜, 장소 정하기 (공통)
- [ ] team, 이슈관리용 repo 생성, 프로토콜버퍼 확인 (종현님)
- [ ] 최소한의 기능으로 러프한 스토리보드 만들어 공유 (현구님)
- [ ] 액션 선정 (선희님)
